linearize: False                            # If joint motions should be linearized

j_speed: 10                                 # Joint motion percentage
j_accel: 50                                 # Joint acceleration percentage

l_speed: 0.05                               # Linear speed override.  Needed for now
l_accel: 5.0                                # Linear acceleration

home: [0.0, -80.0, 100.0, 0.0,-45.0, 0.0] # Axis angles for home position
base: 7                                     # Base frame number
c_dis: 0.5                                  # Cartesian rounding in mm
rtcp: False                                 # Remote Tool Center Point
z_out: False                                # Is Z pointing out of the tool?
tool: -1                                    # Set to a number other than -1 to override tool nnumber